[Addon]
Name=QML Panel
Name[fr]=Panneau QML
Comment=Qt Quick candidate panel for the predictive IME
Category=UI
Version=0.1
Library=libqmlpanel
Type=SharedLibrary
OnDemand=False
Configurable=False

[Addon/Dependencies]
0=core
1=wayland
2=waylandim
